import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
// import { Provider } from "@/nextjs";
import Header from "../components/Header";



const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
       <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>
      <body className={inter.className}>

        <Header/>
        
        {children}</body>
    </html>
    
  );
}
